name: Java CI with Maven

on:
  schedule:
    - cron: '30 5 31 7 *'  # 31st July only at 05:30 UTC = 11:00 AM IST

  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
